<?xml version="1.0" encoding="utf-8"?><Database Name="ecnViessmann" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=TIEFWASSER\ECNEXPRESS2008;Initial Catalog=ecnViessmann;Integrated Security=True" SettingsObjectName="viessmannAdr.Properties.Settings" SettingsPropertyName="ecnViessmannConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ecnDataPointTypeEventTypeLink" Member="ecnDataPointTypeEventTypeLink">
    <Type Name="ecnDataPointTypeEventTypeLink">
      <Column Name="CompanyId" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataPointTypeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EventTypeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="ecnEventType_ecnDataPointTypeEventTypeLink" Member="ecnEventType" ThisKey="EventTypeId" OtherKey="Id" Type="ecnEventType" IsForeignKey="true" />
      <Association Name="ecnDatapointType_ecnDataPointTypeEventTypeLink" Member="ecnDatapointType" ThisKey="DataPointTypeId" OtherKey="Id" Type="ecnDatapointType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ecnEventType" Member="ecnEventType">
    <Type Name="ecnEventType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EnumType" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Conversion" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Priority" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Filtercriterion" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Reportingcriterion" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="URL" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DefaultValue" Type="System.String" DbType="VarChar(1024)" CanBeNull="true" />
      <Column Name="ObjectId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ecnEventType_ecnDataPointTypeEventTypeLink" Member="ecnDataPointTypeEventTypeLink" ThisKey="Id" OtherKey="EventTypeId" Type="ecnDataPointTypeEventTypeLink" />
      <Association Name="ecnEventType_ecnDisplayCondition" Member="ecnDisplayCondition" ThisKey="Id" OtherKey="EventTypeIdCondition" Type="ecnDisplayCondition" />
      <Association Name="ecnEventType_ecnDisplayConditionGroup" Member="ecnDisplayConditionGroup" ThisKey="Id" OtherKey="EventTypeIdDest" Type="ecnDisplayConditionGroup" />
      <Association Name="ecnEventType_ecnEventTypeEventTypeGroupLink" Member="ecnEventTypeEventTypeGroupLink" ThisKey="Id" OtherKey="EventTypeId" Type="ecnEventTypeEventTypeGroupLink" />
      <Association Name="ecnEventType_ecnEventGroupValueCache" Member="ecnEventGroupValueCache" ThisKey="Id" OtherKey="EventTypeId" Type="ecnEventGroupValueCache" />
    </Type>
  </Table>
  <Table Name="dbo.ecnDatapointType" Member="ecnDatapointType">
    <Type Name="ecnDatapointType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StatusEventTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Association Name="ecnDatapointType_ecnDataPointTypeEventTypeLink" Member="ecnDataPointTypeEventTypeLink" ThisKey="Id" OtherKey="DataPointTypeId" Type="ecnDataPointTypeEventTypeLink" />
      <Association Name="ecnDatapointType_ecnEventTypeGroup" Member="ecnEventTypeGroup" ThisKey="Id" OtherKey="DataPointTypeId" Type="ecnEventTypeGroup" />
      <Association Name="ecnDatapointType_ecnDataPoint" Member="ecnDataPoint" ThisKey="Id" OtherKey="DataPointTypeId" Type="ecnDataPoint" />
    </Type>
  </Table>
  <Table Name="dbo.ecnDisplayCondition" Member="ecnDisplayCondition">
    <Type Name="ecnDisplayCondition">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ConditionGroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventTypeIdCondition" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventTypeValueCondition" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EqualCondition" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="ecnDisplayCondition_ecnEventGroupValueCache" Member="ecnEventGroupValueCache" ThisKey="EventTypeIdCondition,EventTypeValueCondition" OtherKey="EventTypeId,EventValueTypeId" Type="ecnEventGroupValueCache" />
      <Association Name="ecnDisplayConditionGroup_ecnDisplayCondition" Member="ecnDisplayConditionGroup" ThisKey="ConditionGroupId" OtherKey="Id" Type="ecnDisplayConditionGroup" IsForeignKey="true" />
      <Association Name="ecnEventType_ecnDisplayCondition" Member="ecnEventType" ThisKey="EventTypeIdCondition" OtherKey="Id" Type="ecnEventType" IsForeignKey="true" />
      <Association Name="ecnEventValueType_ecnDisplayCondition" Member="ecnEventValueType" ThisKey="EventTypeValueCondition" OtherKey="Id" Type="ecnEventValueType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ecnDisplayConditionGroup" Member="ecnDisplayConditionGroup">
    <Type Name="ecnDisplayConditionGroup">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EventTypeIdDest" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EventTypeGroupIdDest" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ecnDisplayConditionGroup_ecnDisplayCondition" Member="ecnDisplayCondition" ThisKey="Id" OtherKey="ConditionGroupId" Type="ecnDisplayCondition" />
      <Association Name="ecnEventTypeGroup_ecnDisplayConditionGroup" Member="ecnEventTypeGroup" ThisKey="EventTypeGroupIdDest" OtherKey="Id" Type="ecnEventTypeGroup" IsForeignKey="true" />
      <Association Name="ecnEventType_ecnDisplayConditionGroup" Member="ecnEventType" ThisKey="EventTypeIdDest" OtherKey="Id" Type="ecnEventType" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ecnEventTypeGroup" Member="ecnEventTypeGroup">
    <Type Name="ecnEventTypeGroup">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ObjectGroupId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ParentId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EntrancePoint" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DeviceTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DataPointTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OrderIndex" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ecnEventTypeGroup_ecnDisplayConditionGroup" Member="ecnDisplayConditionGroup" ThisKey="Id" OtherKey="EventTypeGroupIdDest" Type="ecnDisplayConditionGroup" />
      <Association Name="ecnEventTypeGroup_ecnEventTypeGroup" Member="ecnEventTypeGroup2" ThisKey="Id" OtherKey="ParentId" Type="ecnEventTypeGroup" />
      <Association Name="ecnEventTypeGroup_ecnEventTypeEventTypeGroupLink" Member="ecnEventTypeEventTypeGroupLink" ThisKey="Id" OtherKey="EventTypeGroupId" Type="ecnEventTypeEventTypeGroupLink" />
      <Association Name="ecnDatapointType_ecnEventTypeGroup" Member="ecnDatapointType" ThisKey="DataPointTypeId" OtherKey="Id" Type="ecnDatapointType" IsForeignKey="true" />
      <Association Name="ecnEventTypeGroup_ecnEventTypeGroup" Member="ecnEventTypeGroup1" ThisKey="ParentId" OtherKey="Id" Type="ecnEventTypeGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ecnEventTypeEventTypeGroupLink" Member="ecnEventTypeEventTypeGroupLink">
    <Type Name="ecnEventTypeEventTypeGroupLink">
      <Column Name="CompanyId" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EventTypeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EventTypeGroupId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EventTypeOrder" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ecnEventType_ecnEventTypeEventTypeGroupLink" Member="ecnEventType" ThisKey="EventTypeId" OtherKey="Id" Type="ecnEventType" IsForeignKey="true" />
      <Association Name="ecnEventTypeGroup_ecnEventTypeEventTypeGroupLink" Member="ecnEventTypeGroup" ThisKey="EventTypeGroupId" OtherKey="Id" Type="ecnEventTypeGroup" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ecnEventValueType" Member="ecnEventValueType">
    <Type Name="ecnEventValueType">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="EnumAddressValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EnumReplaceValue" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="StatusTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DataType" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Stepping" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="ValuePrecision" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LowerBorder" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="UpperBorder" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Length" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="ecnEventValueType_ecnDisplayCondition" Member="ecnDisplayCondition" ThisKey="Id" OtherKey="EventTypeValueCondition" Type="ecnDisplayCondition" />
      <Association Name="ecnEventValueType_ecnEventGroupValueCache" Member="ecnEventGroupValueCache" ThisKey="Id,CompanyId" OtherKey="EventValueTypeId,CompanyId" Type="ecnEventGroupValueCache" />
    </Type>
  </Table>
  <Table Name="dbo.ecnEventGroupValueCache" Member="ecnEventGroupValueCache">
    <Type Name="ecnEventGroupValueCache">
      <Column Name="CompanyId" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DeviceId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="DataPointId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EventTypeId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="EventValueTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ValueState" Type="System.Byte" DbType="TinyInt NOT NULL" CanBeNull="false" />
      <Column Name="StatusTypeId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ValueType" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Value_Bit" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Value_Int" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Value_Float" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Value_Ntext" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Value_VarChar" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Value_DateTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Value_Binary" Type="System.Data.Linq.Binary" DbType="VarBinary(8000)" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="ValueUnit" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ValueEventTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="ecnEventValueType_ecnEventGroupValueCache" Member="ecnEventValueType" ThisKey="EventValueTypeId,CompanyId" OtherKey="Id,CompanyId" Type="ecnEventValueType" IsForeignKey="true" />
      <Association Name="ecnEventType_ecnEventGroupValueCache" Member="ecnEventType" ThisKey="EventTypeId" OtherKey="Id" Type="ecnEventType" IsForeignKey="true" />
      <Association Name="ecnDisplayCondition_ecnEventGroupValueCache" Member="ecnDisplayCondition" ThisKey="EventTypeId,EventValueTypeId" OtherKey="EventTypeIdCondition,EventTypeValueCondition" Type="ecnDisplayCondition" IsForeignKey="true" />
      <Association Name="ecnDataPoint_ecnEventGroupValueCache" Member="ecnDataPoint" ThisKey="DataPointId,CompanyId" OtherKey="Id,CompanyId" Type="ecnDataPoint" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ecnDataPoint" Member="ecnDataPoint">
    <Type Name="ecnDataPoint">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CompanyId" Type="System.Byte" DbType="TinyInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="DataPointTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DeviceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="InformationDataSetXML" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="StatusEventTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Deleted" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="ecnDataPoint_ecnEventGroupValueCache" Member="ecnEventGroupValueCache" ThisKey="Id,CompanyId" OtherKey="DataPointId,CompanyId" Type="ecnEventGroupValueCache" />
      <Association Name="ecnDatapointType_ecnDataPoint" Member="ecnDatapointType" ThisKey="DataPointTypeId" OtherKey="Id" Type="ecnDatapointType" IsForeignKey="true" />
    </Type>
  </Table>
</Database>