//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace viessmannAdr
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisplayCondition
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int ConditionGroupId { get; set; }
        public int EventTypeIdCondition { get; set; }
        public int EventTypeValueCondition { get; set; }
        public string Description { get; set; }
        public int Condition { get; set; }
        public Nullable<double> ConditionValue { get; set; }
    
        public virtual EventValueType EventValueCondition { get; set; }
        public virtual DisplayConditionGroup DisplayConditionGroup { get; set; }
        public virtual EventType EventTypeCondition { get; set; }
    }
}
