//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System. Collections. ObjectModel;
    
    public partial class EventGroupValue
    {
        public int DeviceId { get; set; }
        public int DataPointId { get; set; }
        public int EventTypeId { get; set; }
        public int EventValueTypeId { get; set; }
        public byte ValueState { get; set; }
        public Nullable<int> StatusTypeId { get; set; }
        public Nullable<int> ValueType { get; set; }
        public Nullable<bool> Value_Bit { get; set; }
        public Nullable<int> Value_Int { get; set; }
        public Nullable<double> Value_Float { get; set; }
        public string Value_Ntext { get; set; }
        public string Value_VarChar { get; set; }
        public Nullable<System.DateTime> Value_DateTime { get; set; }
        public byte[] Value_Binary { get; set; }
        public string ValueUnit { get; set; }
        public System.DateTime ValueEventTime { get; set; }
    
        public virtual DataPoint ecnDataPoint { get; set; }
        public virtual EventValueType ecnEventValueType { get; set; }
        public virtual StatusType ecnStatusType { get; set; }
    }
}
