//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System. Collections. ObjectModel;
    
    public partial class EventTypeGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventTypeGroup()
        {
            this.DisplayConditionGroups = new ObservableCollection<DisplayConditionGroup>();
            this.EventTypeLinks = new ObservableCollection<EventTypeEventTypeGroupLink>();
            this.ChildEventTypeGroups = new ObservableCollection<EventTypeGroup>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int ObjectGroupId { get; set; }
        public int ParentId { get; set; }
        public bool EntrancePoint { get; set; }
        public string Address { get; set; }
        public int DeviceTypeId { get; set; }
        public int DataPointTypeId { get; set; }
        public int OrderIndex { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<DisplayConditionGroup> DisplayConditionGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<EventTypeEventTypeGroupLink> EventTypeLinks { get; set; }
        public virtual DatapointType DatapointType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<EventTypeGroup> ChildEventTypeGroups { get; set; }
        public virtual EventTypeGroup ParentEventTypeGroup { get; set; }
    }
}
