//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System. Collections. ObjectModel;
    
    public partial class EventValueType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventValueType()
        {
            this.EventGroupValues = new ObservableCollection<EventGroupValue>();
            this.EventTypes = new ObservableCollection<EventType>();
            this.DisplayConditions = new ObservableCollection<DisplayCondition>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> EnumAddressValue { get; set; }
        public string EnumReplaceValue { get; set; }
        public int StatusTypeId { get; set; }
        public string Unit { get; set; }
        public string DataType { get; set; }
        public Nullable<double> Stepping { get; set; }
        public Nullable<int> ValuePrecision { get; set; }
        public Nullable<double> LowerBorder { get; set; }
        public Nullable<double> UpperBorder { get; set; }
        public Nullable<int> Length { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<EventGroupValue> EventGroupValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<EventType> EventTypes { get; set; }
        public virtual StatusType StatusType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<DisplayCondition> DisplayConditions { get; set; }
    }
}
