//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System. Collections. ObjectModel;
    
    public partial class EventType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EventType()
        {
            this.DatapointTypes = new ObservableCollection<DatapointType>();
            this.EventValueTypes = new ObservableCollection<EventValueType>();
            this.EventTypeGroupLinks = new ObservableCollection<EventTypeEventTypeGroupLink>();
            this.DisplayConditions = new ObservableCollection<DisplayCondition>();
            this.DisplayConditionGroups = new ObservableCollection<DisplayConditionGroup>();
        }
    
        public int Id { get; set; }
        public bool EnumType { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Conversion { get; set; }
        public string Description { get; set; }
        public int Priority { get; set; }
        public bool Filtercriterion { get; set; }
        public bool Reportingcriterion { get; set; }
        public int Type { get; set; }
        public string URL { get; set; }
        public string DefaultValue { get; set; }
        public int ObjectId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<DatapointType> DatapointTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<EventValueType> EventValueTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<EventTypeEventTypeGroupLink> EventTypeGroupLinks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<DisplayCondition> DisplayConditions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<DisplayConditionGroup> DisplayConditionGroups { get; set; }
    }
}
