//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System. Collections. ObjectModel;
    
    public partial class EventTypeEventTypeGroupLink
    {
        public int EventTypeId { get; set; }
        public int EventTypeGroupId { get; set; }
        public int EventTypeOrder { get; set; }
    
        public virtual EventTypeGroup EventTypeGroup { get; set; }
        public virtual EventType EventType { get; set; }
    }
}
