//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ViessmannEntities : DbContext
    {
        public ViessmannEntities()
            : base("name=ViessmannEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DataPoint> DataPoints { get; set; }
        public virtual DbSet<DatapointTypeGroup> DatapointTypeGroups { get; set; }
        public virtual DbSet<DatapointType> DatapointTypes { get; set; }
        public virtual DbSet<EventGroupValue> EventGroupValues { get; set; }
        public virtual DbSet<EventType> EventTypes { get; set; }
        public virtual DbSet<EventTypeEventTypeGroupLink> EventTypeEventTypeGroupLinks { get; set; }
        public virtual DbSet<EventTypeGroup> EventTypeGroups { get; set; }
        public virtual DbSet<EventValueType> EventValueTypes { get; set; }
        public virtual DbSet<DisplayCondition> DisplayConditions { get; set; }
        public virtual DbSet<DisplayConditionGroup> DisplayConditionGroups { get; set; }
        public virtual DbSet<StatusType> StatusTypes { get; set; }
    }
}
